# Setup
port: 4000
host: 0.0.0.0

title: NLP-OSS
tagline: Democratizing NLP!
keywords: "Natural Language Processing, NLP, Open Source Software, OSS, Workshop"
description: "Workshop for NLP Open Source Software (NLP-OSS)"
google_analytics_key: UA-157382521-1

url: https://nlposs.github.io
baseurl: ""
permalink: :title/  # disables post output
timezone: null
lsi: false
markdown: kramdown
kramdown:
    footnote_backlink: "&#10548;"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank
  - jekyll-redirect-from

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed
